name: Production Pipeline

on:
  release:
    types:
      - published
 
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: xdebug
          extensions: grpc
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --seed
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --coverage --min=65
  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy-production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: api-user@cashingames.com
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            fileToExclude.txt
      - name: install_dependencies
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd stg-api
            /opt/cpanel/composer/bin/composer install --optimize-autoloader --no-dev
          host: mocha3031.mochahost.com
          username: cashinga
          password: ${{ secrets.CPANEL_PASSWORD }}
      - name: optimize_deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd api
            php artisan optimize
            php artisan config:cache
            php artisan route:cache
            php artisan event:cache
            php artisan view:cache
          host: mocha3031.mochahost.com
          username: cashinga
          password: ${{ secrets.CPANEL_PASSWORD }}
      - name: migrate_staging
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd api && php artisan migrate
          host: mocha3031.mochahost.com
          username: cashinga
          password: ${{ secrets.CPANEL_PASSWORD }}